name: pricing
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_svg: ^1.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: SFPRODISPLAY
      fonts:
        - asset: fonts/SFPRODISPLAYBLACKITALIC.OTF
        - asset: fonts/SFPRODISPLAYBOLD.OTF
        - asset: fonts/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: fonts/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: fonts/SFPRODISPLAYREGULAR.OTF
        - asset: fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: fonts/SFPRODISPLAYTHINITALIC.OTF
        - asset: fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF


